### ISSUE TITLE
Deleted items still wisible by tester

### ISSUE THREAD

**Issue by krida2000** [robert-luoqing/flutter_list_view#16]
I faced with issue when I remove items from `FlutterListView` they still visible by tester. 

You can reproduce this problem by runing test in this project https://github.com/krida2000/flutter_list_view_problem.

This problem fixed by uncoment this code: 
![image](https://user-images.githubusercontent.com/71345244/199021304-d72433fe-18ce-46df-8c72-a8b6cc9f43f1.png)

Can wee just uncoment this code or there is a better solution?

**Comment by robert-luoqing** [comment]
@krida2000 Sorry for late reply. This is by design.

In flutter list view, All items will be reused even though these items is deactive. it just cached and invisible.  So it can fetch via render object tree. 

BTW, I have add disableCacheItems under FlutterListViewDelegate like below code. the version is 1.1.19. If you don't want cache those items[It may have a little performance impact]. please set the disableCacheItems to true
```
FlutterListView(
    controller: controller,
    delegate: FlutterListViewDelegate(
      (BuildContext context, int index) => Item(
        text: data[index],
        color: colors[index],
        height: heights[index],
      ),
      childCount: data.length,
      preferItemHeight: 50,
      // onItemHeight: (context) => 33
      disableCacheItems: disableCache,
    ),
  )
```
