### ISSUE TITLE
[cacheExtent] is ineffective

### ISSUE THREAD

**Issue by jiangtian616** [robert-luoqing/flutter_list_view#9]
Hi! Thanks for your great work, but i'm stuck in setting `cacheExtent`.

Example code:
```dart
class HomePage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return FlutterListView(
      cacheExtent: 500,
      delegate: FlutterListViewDelegate(
        (context, index) {
          print(index);
          return Container(color: Colors.red, height: 50);
        },
        childCount: 500,
        onItemKey: (index) => index.toString(),
        onItemHeight: (index) => 50,
      ),
    );
  }
}
```

For my device, enter this page will get index outputs 1 to 34. But if i change `cacheExtent` to another value(no matter what its value is), the outputs is always same(1 to 34). I wonder if there's any mistake in my code?

**Comment by robert-bitguild** [comment]
It is not an error because FlutterListView ignored the cacheExtent based on the reused existing items. I worked with React Native. I guess the cacheExtent is used to resolve the scrolling smooth issue.  Here is not necessary to implement it.

But I will implement it if you have a special requirement that needs cacheExtent.

**Comment by robert-luoqing** [comment]
@jiangtian616 The lib has implemented cacheExtent, please update it to flutter_list_view: ^1.1.13.

Thanks

**Comment by jiangtian616** [comment]
Thanks a lot, it takes effect now.
